<?php

use Illuminate\Database\Seeder;

class LoadDummyQuestions extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('accounting')->insert(['question' => 'The bad debt account is closed by transferring the balance to','optionA' => 'credit of capital account', 'optionB' => 'debit of profit  and loss', 'optionC' => 'debit of the debtors personal account','optionD' => 'credit of profit and loss account', 'answer' => 'a', 'examtype' => 'JAMB', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('accounting')->insert(['question' => 'The bad  account is closed','optionA' => 'capital account', 'optionB' => 'debit of profit  ', 'optionC' => 'debit of account','optionD' => 'credit of profit account', 'answer' => 'b', 'examtype' => 'JAMB', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('accounting')->insert(['question' => 'The bad debt account o','optionA' => 'credit', 'optionB' => 'debitband loss', 'optionC' => ' account','optionD' => 'credit of profit and loss account', 'answer' => 'c', 'examtype' => 'WAEC', 'examyear' => '2008', 'authorised' => 'Admin',]);
        DB::table('accounting')->insert(['question' => 'Bad debt account','optionA' => 'credit of capital account', 'optionB' => 'debit of profit  and loss', 'optionC' => 'debit of the debtors personal account','optionD' => 'credit of profit and loss account', 'answer' => 'd', 'examtype' => 'WAEC', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('accounting')->insert(['question' => 'Bad account','optionA' => 'credit', 'optionB' => 'loss', 'optionC' => 'debit o account','optionD' => 'credit of profit ', 'answer' => 'a', 'examtype' => 'JAMB', 'examyear' => '2008', 'authorised' => 'Admin',]);

        DB::table('english')->insert(['question' => 'The bad debt account is closed by transferring the balance to','optionA' => 'credit of capital account', 'optionB' => 'debit of profit  and loss', 'optionC' => 'debit of the debtors personal account','optionD' => 'credit of profit and loss account', 'answer' => 'a', 'examtype' => 'JAMB', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('english')->insert(['question' => 'The bad  account is closed','optionA' => 'capital account', 'optionB' => 'debit of profit  ', 'optionC' => 'debit of account','optionD' => 'credit of profit account', 'answer' => 'b', 'examtype' => 'JAMB', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('english')->insert(['question' => 'The bad debt account o','optionA' => 'credit', 'optionB' => 'debitband loss', 'optionC' => ' account','optionD' => 'credit of profit and loss account', 'answer' => 'c', 'examtype' => 'WAEC', 'examyear' => '2008', 'authorised' => 'Admin',]);
        DB::table('english')->insert(['question' => 'Bad debt account','optionA' => 'credit of capital account', 'optionB' => 'debit of profit  and loss', 'optionC' => 'debit of the debtors personal account','optionD' => 'credit of profit and loss account', 'answer' => 'd', 'examtype' => 'WAEC', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('english')->insert(['question' => 'Bad account','optionA' => 'credit', 'optionB' => 'loss', 'optionC' => 'debit o account','optionD' => 'credit of profit ', 'answer' => 'a', 'examtype' => 'JAMB', 'examyear' => '2008', 'authorised' => 'Admin',]);

        DB::table('mathematics')->insert(['question' => 'The bad debt account is closed by transferring the balance to','optionA' => 'credit of capital account', 'optionB' => 'debit of profit  and loss', 'optionC' => 'debit of the debtors personal account','optionD' => 'credit of profit and loss account', 'answer' => 'a', 'examtype' => 'JAMB', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('mathematics')->insert(['question' => 'The bad  account is closed','optionA' => 'capital account', 'optionB' => 'debit of profit  ', 'optionC' => 'debit of account','optionD' => 'credit of profit account', 'answer' => 'b', 'examtype' => 'JAMB', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('mathematics')->insert(['question' => 'The bad debt account o','optionA' => 'credit', 'optionB' => 'debitband loss', 'optionC' => ' account','optionD' => 'credit of profit and loss account', 'answer' => 'c', 'examtype' => 'WAEC', 'examyear' => '2008', 'authorised' => 'Admin',]);
        DB::table('mathematics')->insert(['question' => 'Bad debt account','optionA' => 'credit of capital account', 'optionB' => 'debit of profit  and loss', 'optionC' => 'debit of the debtors personal account','optionD' => 'credit of profit and loss account', 'answer' => 'd', 'examtype' => 'WAEC', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('mathematics')->insert(['question' => 'Bad account','optionA' => 'credit', 'optionB' => 'loss', 'optionC' => 'debit o account','optionD' => 'credit of profit ', 'answer' => 'a', 'examtype' => 'JAMB', 'examyear' => '2008', 'authorised' => 'Admin',]);

        DB::table('physics')->insert(['question' => 'The bad debt account is closed by transferring the balance to','optionA' => 'credit of capital account', 'optionB' => 'debit of profit  and loss', 'optionC' => 'debit of the debtors personal account','optionD' => 'credit of profit and loss account', 'answer' => 'a', 'examtype' => 'JAMB', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('physics')->insert(['question' => 'The bad  account is closed','optionA' => 'capital account', 'optionB' => 'debit of profit  ', 'optionC' => 'debit of account','optionD' => 'credit of profit account', 'answer' => 'b', 'examtype' => 'JAMB', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('physics')->insert(['question' => 'The bad debt account o','optionA' => 'credit', 'optionB' => 'debitband loss', 'optionC' => ' account','optionD' => 'credit of profit and loss account', 'answer' => 'c', 'examtype' => 'WAEC', 'examyear' => '2008', 'authorised' => 'Admin',]);
        DB::table('physics')->insert(['question' => 'Bad debt account','optionA' => 'credit of capital account', 'optionB' => 'debit of profit  and loss', 'optionC' => 'debit of the debtors personal account','optionD' => 'credit of profit and loss account', 'answer' => 'd', 'examtype' => 'WAEC', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('physics')->insert(['question' => 'Bad account','optionA' => 'credit', 'optionB' => 'loss', 'optionC' => 'debit o account','optionD' => 'credit of profit ', 'answer' => 'a', 'examtype' => 'JAMB', 'examyear' => '2008', 'authorised' => 'Admin',]);

        DB::table('chemistry')->insert(['question' => 'The bad debt account is closed by transferring the balance to','optionA' => 'credit of capital account', 'optionB' => 'debit of profit  and loss', 'optionC' => 'debit of the debtors personal account','optionD' => 'credit of profit and loss account', 'answer' => 'a', 'examtype' => 'JAMB', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('chemistry')->insert(['question' => 'The bad  account is closed','optionA' => 'capital account', 'optionB' => 'debit of profit  ', 'optionC' => 'debit of account','optionD' => 'credit of profit account', 'answer' => 'b', 'examtype' => 'JAMB', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('chemistry')->insert(['question' => 'The bad debt account o','optionA' => 'credit', 'optionB' => 'debitband loss', 'optionC' => ' account','optionD' => 'credit of profit and loss account', 'answer' => 'c', 'examtype' => 'WAEC', 'examyear' => '2008', 'authorised' => 'Admin',]);
        DB::table('chemistry')->insert(['question' => 'Bad debt account','optionA' => 'credit of capital account', 'optionB' => 'debit of profit  and loss', 'optionC' => 'debit of the debtors personal account','optionD' => 'credit of profit and loss account', 'answer' => 'd', 'examtype' => 'WAEC', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('chemistry')->insert(['question' => 'Bad account','optionA' => 'credit', 'optionB' => 'loss', 'optionC' => 'debit o account','optionD' => 'credit of profit ', 'answer' => 'a', 'examtype' => 'JAMB', 'examyear' => '2008', 'authorised' => 'Admin',]);

        DB::table('biology')->insert(['question' => 'The bad debt account is closed by transferring the balance to','optionA' => 'credit of capital account', 'optionB' => 'debit of profit  and loss', 'optionC' => 'debit of the debtors personal account','optionD' => 'credit of profit and loss account', 'answer' => 'a', 'examtype' => 'JAMB', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('biology')->insert(['question' => 'The bad  account is closed','optionA' => 'capital account', 'optionB' => 'debit of profit  ', 'optionC' => 'debit of account','optionD' => 'credit of profit account', 'answer' => 'b', 'examtype' => 'JAMB', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('biology')->insert(['question' => 'The bad debt account o','optionA' => 'credit', 'optionB' => 'debitband loss', 'optionC' => ' account','optionD' => 'credit of profit and loss account', 'answer' => 'c', 'examtype' => 'WAEC', 'examyear' => '2008', 'authorised' => 'Admin',]);
        DB::table('biology')->insert(['question' => 'Bad debt account','optionA' => 'credit of capital account', 'optionB' => 'debit of profit  and loss', 'optionC' => 'debit of the debtors personal account','optionD' => 'credit of profit and loss account', 'answer' => 'd', 'examtype' => 'WAEC', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('biology')->insert(['question' => 'Bad account','optionA' => 'credit', 'optionB' => 'loss', 'optionC' => 'debit o account','optionD' => 'credit of profit ', 'answer' => 'a', 'examtype' => 'JAMB', 'examyear' => '2008', 'authorised' => 'Admin',]);

        DB::table('commerce')->insert(['question' => 'The bad debt account is closed by transferring the balance to','optionA' => 'credit of capital account', 'optionB' => 'debit of profit  and loss', 'optionC' => 'debit of the debtors personal account','optionD' => 'credit of profit and loss account', 'answer' => 'a', 'examtype' => 'JAMB', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('commerce')->insert(['question' => 'The bad  account is closed','optionA' => 'capital account', 'optionB' => 'debit of profit  ', 'optionC' => 'debit of account','optionD' => 'credit of profit account', 'answer' => 'b', 'examtype' => 'JAMB', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('commerce')->insert(['question' => 'The bad debt account o','optionA' => 'credit', 'optionB' => 'debitband loss', 'optionC' => ' account','optionD' => 'credit of profit and loss account', 'answer' => 'c', 'examtype' => 'WAEC', 'examyear' => '2008', 'authorised' => 'Admin',]);
        DB::table('commerce')->insert(['question' => 'Bad debt account','optionA' => 'credit of capital account', 'optionB' => 'debit of profit  and loss', 'optionC' => 'debit of the debtors personal account','optionD' => 'credit of profit and loss account', 'answer' => 'd', 'examtype' => 'WAEC', 'examyear' => '2006', 'authorised' => 'Admin',]);
        DB::table('commerce')->insert(['question' => 'Bad account','optionA' => 'credit', 'optionB' => 'loss', 'optionC' => 'debit o account','optionD' => 'credit of profit ', 'answer' => 'a', 'examtype' => 'JAMB', 'examyear' => '2008', 'authorised' => 'Admin',]);
    }
}
